decaydelay: 20 # Delay between block changes in ticks. There are 20 ticks/second.
radius: 50 # The radius around the player in which blocks will be changed.
protectspecblocks: true # Protect special blocks, such as furnaces, beds, etc. Options are true and false
effectliquids: false # Stop from using liquids, which take over and lag out the server at high altitudes